# Generated by Django 2.1.7 on 2019-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_claim_processedclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedclaim',
            name='image_denoised',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
