# Generated by Django 2.1.7 on 2019-03-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
