# Generated by Django 2.1.7 on 2019-03-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.CharField(max_length=100),
        ),
    ]
