# Generated by Django 2.1.7 on 2019-04-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190328_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
